<div class="story-react-wrapper">
	<span data-title="Like" onclick="set_reaction('like', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_like.png" alt="Like">
	</span>

	<span data-title="Love" onclick="set_reaction('love', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_love.png" alt="Love" data-title="Love">
	</span>

	<span data-title="Haha" onclick="set_reaction('haha', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_haha.png" alt="Haha" data-title="Haha">
	</span>

	<span data-title="Wow" onclick="set_reaction('wow', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_wow.png" alt="Wow" data-title="Wow">
	</span>

	<span data-title="Sad" onclick="set_reaction('sad', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_sad.png" alt="Sad" data-title="Sad">
	</span>
	
	<span data-title="Angry" onclick="set_reaction('angry', {{STORY_ID}});">
		<img src="{{CONFIG_SITE_URL}}/assets/imgs/reaction_angry.png" alt="Angry" data-title="Angry">
	</span>
</div>