<div class="page-margin"></div>

<div class="float-left span25">
    <div class="list-wrapper">
        <div class="list-header">
            @menu_label@
        </div>
        
        <a class="list-column" href="{{GENERAL_SETTINGS_URL}}" data-href="?tab1=settings&tab2=general">
            @general_settings_label@
        </a>
        
        <a class="list-column" href="{{PRIVACY_SETTINGS_URL}}" data-href="?tab1=settings&tab2=privacy">
            @privacy_settings_label@
        </a>

        <a class="list-column" href="{{EMAIL_NOTIFICATION_SETTINGS_URL}}" data-href="?tab1=settings&tab2=email_notifications">
            @email_notifications_label@
        </a>
        
        <a class="list-column" href="{{AVATAR_SETTINGS_URL}}" data-href="?tab1=settings&tab2=avatar">
            @timeline_avatar_label@
        </a>
        
        <a class="list-column" href="{{COVER_SETTINGS_URL}}" data-href="?tab1=settings&tab2=cover">
            @timeline_cover_label@
        </a>
        
        <a class="list-column" href="{{PASSWORD_SETTINGS_URL}}" data-href="?tab1=settings&tab2=password">
            @password_label@
        </a>

        <a class="list-column" href="{{DEACTIVATE_URL}}" data-href="?tab1=settings&tab2=deactivate">
            @deactivate_account_label@
        </a>
    </div>
</div>

<div class="float-right span74">
    {{TAB_CONTENT}}
</div>

<div class="float-clear"></div>