<div class="footer-wrapper">
    <div class="footer-content" align="center">
        <div class="footer-line">
            {{FOOTER_PAGES}}
        </div>
        
        <div class="footer-line">
            @languages_label@: 
            
            {{LANGUAGES}}
        </div>
        
        <div class="footer-line">
            @copyright@ &#169; {{YEAR}} {{CONFIG_SITE_NAME}}. @all_rights_reserved@.
        </div>
    </div>
</div>