<form class="update-timeline-form" method="post">
    <div class="form-container">
        <div class="form-header">
            @email_notifications_label@
        </div>
        
        {{FOLLOW_EMAIL_ROW}}

        {{FRIENDREQUEST_EMAIL_ROW}}
        
        <div class="form-input-wrapper">
            <div class="input float-left span5">
                <input type="checkbox" name="mailnotif_comment" value="1" {{COMMENT_EMAIL_NOTIFICATION_CHECKED}}>
            </div>

            <label class="float-left span50">
                @email_notification_comment_label@
            </label>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <div class="input float-left span5">
                <input type="checkbox" name="mailnotif_postlike" value="1" {{POSTLIKE_EMAIL_NOTIFICATION_CHECKED}}>
            </div>

            <label class="float-left span50">
                @email_notification_postlike_label@
            </label>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <div class="input float-left span5">
                <input type="checkbox" name="mailnotif_postshare" value="1" {{POSTSHARE_EMAIL_NOTIFICATION_CHECKED}}>
            </div>

            <label class="float-left span50">
                @email_notification_postshare_label@
            </label>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <div class="input float-left span5">
                <input type="checkbox" name="mailnotif_groupjoined" value="1" {{GROUPJOINED_EMAIL_NOTIFICATION_CHECKED}}>
            </div>

            <label class="float-left span50">
                @email_notification_groupjoined_label@
            </label>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <div class="input float-left span5">
                <input type="checkbox" name="mailnotif_pagelike" value="1" {{PAGELIKE_EMAIL_NOTIFICATION_CHECKED}}>
            </div>

            <label class="float-left span50">
                @email_notification_pagelike_label@
            </label>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <div class="input float-left span5">
                <input type="checkbox" name="mailnotif_message" value="1" {{MESSAGE_EMAIL_NOTIFICATION_CHECKED}}>
            </div>

            <label class="float-left span50">
                @email_notification_message_label@
            </label>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <div class="input float-left span5">
                <input type="checkbox" name="mailnotif_timelinepost" value="1" {{TIMELINEPOST_EMAIL_NOTIFICATION_CHECKED}}>
            </div>

            <label class="float-left span50">
                @email_notification_timelinepost_label@
            </label>

            <div class="float-clear"></div>
        </div>

        <div class="form-input-wrapper">
            <button class="active">
                <i class="icon-lightbulb progress-icon hide"></i> 
                @save_changes_button@
            </button>
        </div>
    </div>

    <input type="hidden" name="username" value="{{USER_USERNAME}}">
    <input type="hidden" name="mailnotif_settings" value="1">
</form>

<script>
$('form.update-timeline-form').ajaxForm({
    url: SK_source()+'?t=user&a=settings',
    
    beforeSend: function () {
        SK_progressIconLoader($('form.update-timeline-form').find('button'));
    },
    
    success: function (responseText) {
        if (responseText.status == 200) {
            
            $('.form-header').after('<div class="success-message hidden">@changes_saved@</div>');
            $('.success-message').fadeIn('fast',function () {
                    $(this).fadeOut(1500, function() {
                        $(this).remove();
                    });
                });
        }
        
        SK_progressIconLoader($('form.update-timeline-form').find('button'));
    }
});
</script>